name: Gradle Check
on: [push, pull_request]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          - distribution: "temurin"
          - java-version: "19"
      - name: Set Up Gradle
        uses: gradle/gradle-build-action@v2
      - name: Gradle Check
        run: ./gradlew build
